### ISSUE TITLE
Copy/paste: implement "Copy" menu in frontend

### ISSUE THREAD

**Issue by ormsbee** [openedx/modular-learning#10]
For users with the feature flag #11 active, display the new "Copy" action in the Studio menu #50. Clicking it should use the new backend copy API from #51 to copy the component onto the clipboard. Display the status as a toast per [the wireframes](https://www.figma.com/file/y2qfzidTxxfYK8ONgyT7KP/Modular-Learning-Wireframes):

![Screenshot 2023-02-17 at 2 28 47 PM](https://user-images.githubusercontent.com/945577/219806249-ed3bdfc1-341a-4a59-855f-3266eb55e511.png)

![Screenshot 2023-02-17 at 2 28 59 PM](https://user-images.githubusercontent.com/945577/219806366-8f6cb831-24ca-44f9-aa94-bcac3476c02a.png)

**Comment by bradenmacdonald** [comment]
@ali-hugo It turns out that these existing Studio "toasts" don't support a "Complete" message; they just disappear when they're done. So it can say "Copying component" with the gear spinning, but there's no easy way to display "Copied!" without the gear spinning, and if I do so it would be different than all the other similar notifications in Studio. I can still find a way to implement it but it will take longer. How important is the "Copied!" success message? I can always create a separate task to implement it later if we have extra time.

**Comment by ali-hugo** [comment]
@bradenmacdonald If there's time left over, I think it might be worthwhile implementing the success message. Here's why: When a component is **duplicated**, something happens on the screen (i.e. a second version of the component appears), but when a component is **copied**, nothing changes on the screen, so the user doesn't get any confirmation that the copy was successful. 

That said, it would be interesting to see how test users cope without the success message, so we could always leave it off for now, and add it if usability testing proves it to be necessary. What do you think?

**Comment by bradenmacdonald** [comment]
@ali-hugo  Sure, I think we'll have time so I should be able to take that on.
