### ISSUE TITLE
[Tagging] Per-taxonomy menu on Taxonomy List Page

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#105]
Follows https://github.com/openedx/modular-learning/issues/104 and https://github.com/openedx/modular-learning/issues/113 .

"As any user with access to Studio, I can download any Taxonomy as CSV, if I have permission to view that Taxonomy."

"As any user with access to Studio, I can download any Taxonomy as JSON, if I have permission to view that Taxonomy."

"As any user with access to Studio, I get an explanation of what system-defined taxonomies are."

### Acceptance Criteria
1. Display this [tooltip](https://paragon-openedx.netlify.app/components/tooltip/) when a user hovers over the "System level" badge of a system-defined taxonomy:
    ![Screenshot 2023-10-11 at 2 34 07 PM](https://github.com/openedx/modular-learning/assets/945577/3cace8a2-b378-47c9-b797-fa9cdc26ddf5)
2. Display the "three dots" menu button for all taxonomies, including system-defined taxonomies. Clicking it should show a menu with "Export".
    ![Screenshot 2023-10-12 at 10 00 39 AM](https://github.com/openedx/modular-learning/assets/945577/dde0a901-7763-45e5-8764-546d82c49b4b)
3. Clicking that will lead to this dialog:
    ![Screenshot 2023-10-12 at 10 01 35 AM](https://github.com/openedx/modular-learning/assets/945577/d1ff877d-a560-4b82-9672-2d10cbfb8ce3)
4. Selecting "Export as CSV" or "Export as JSON" should trigger the corresponding export and download the taxonomy as a file, using the API from #113 
5. Other menu items will come in later stories: "Edit Details" in #125, "Re-import" in #140, "Manage Organizations" in #117, and "Delete" in #127.

### Developer Notes

* Screenshots above are for convenience - [Figma](https://www.figma.com/file/DmUC2e7BAoQsGDq4KgApPa/Content-Tagging-MVP) is the most up-to-date source for mockups. The scale of UI elements seen in the screenshots above may be incorrect.

**Comment by bradenmacdonald** [comment]
@ChrisChV is there a REST API to trigger the export of a taxonomy?

**Comment by ChrisChV** [comment]
> @ChrisChV is there a REST API to trigger the export of a taxonomy?

@bradenmacdonald  Whops! No, in the code is missing the REST API to call the import/export. I remember seeing that task/issue somewhere. I've looked for it and can't find anything

**Comment by bradenmacdonald** [comment]
@ChrisChV OK, no problem. I created https://github.com/openedx/modular-learning/issues/113 as a prerequisite for this issue then.

**Comment by ali-hugo** [comment]
@bradenmacdonald 

As the [wireframes currently stand](https://www.figma.com/file/DmUC2e7BAoQsGDq4KgApPa/Content-Tagging-MVP?type=design&node-id=0%3A1&mode=design&t=XTJfiABi2t1MeUmv-1), only global staff can export (i.e. download) taxonomies. 

I imagine things might change once you've received feedback on https://github.com/openedx/modular-learning/issues/129

**Comment by bradenmacdonald** [comment]
@ali-hugo Yes, if someone is an instructor on Site A but is a global staff on Site B, they may wish to download the taxonomy they've been using on Site A and upload it to use on Site B. In general if someone can _view_ the taxonomy there's no reason not to let them _download_ it IMHO, because they could always tediously re-create it step by step if they wanted to anyways.

**Comment by ali-hugo** [comment]
@bradenmacdonald That makes sense to me. I have updated the design accordingly. 

Please note that users with view-only permissions don't see the cog, the lock, nor the "enabled / enabled (default)" tags; they only see the menu with the option to export as CSV and JSON. I don't think it brings much value to these users to know whether the taxonomy is system-defined or not. Let me know if you disagree.

**Comment by ali-hugo** [comment]
@bradenmacdonald @ChrisChV This is all working well for me. Just wanted to flag a few small things (all of which can be fixed at a later stage):

![Screenshot 2023-11-28 at 11 07 07](https://github.com/openedx/modular-learning/assets/88187719/8b1e0736-7ed7-414f-9f79-b81d0b4a4c32)

- Max width of tooltips in Paragon is 300px (the tooltip in the screenshot above looks wider)
- The text in the "system-level" badge should not be bolded

![badge](https://github.com/openedx/modular-learning/assets/88187719/dd99ce8d-6e26-46bf-a455-c2aaf8355d78)

- I noticed there is no way to see whether a taxonomy is system-level or not on the taxonomy detail page. Could we add a "system-level" badge to this page, under the page title (as shown in the mockup above)?

![clickable area](https://github.com/openedx/modular-learning/assets/88187719/f7a52d2c-3764-4861-8ac6-defe498bdd09)

- Could we extend the clickable area to include anything within the blue block in the screenshot above? Instinctively, I tried to click here in order to select the radio button

**Comment by bradenmacdonald** [comment]
^ We will fix the above shortly in FAL-3537.

**Comment by ChrisChV** [comment]
@ali-hugo 
> I noticed there is no way to see whether a taxonomy is system-level or not on the taxonomy detail page. Could we add a "system-level" badge to this page, under the page title (as shown in the mockup above)?

Should this badge show the tooltip?
