### ISSUE TITLE
[Course Search] Refinements to search modal UX

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#211]
Fixes to Paragon:
1. The focus state of the button outline has a rounded edge when it should have a square edge (to match the button shape).
    ![image](https://github.com/openedx/modular-learning/assets/945577/27969101-8f45-45e8-854a-34cafbe1fa7f)

Fixes to our content search modal:

2. Please increase the spacing between the search keywords field and "This Course" so that there are a few pixels between them when the button is focused.
    ![image](https://github.com/openedx/modular-learning/assets/945577/27969101-8f45-45e8-854a-34cafbe1fa7f)
3. For each result, the course/library name should only appear in the breadcrumbs when “all courses” is selected. (Currently, it shows for the results in “this course” too.)
4. If I enter a search term that yields no results, I am unable to open the “type” filter. Change it to behave like the "Tags" filter and display a message like "No types in current results" in that case.
5. When the search modal opens, focus on the search keywords field so the user can start typing right away.
6. **NEW** the number is not visible next to longer filter names (see “Open Response Assessmen...” below. Is it possible to ensure the number is always displayed (if necessary by making the menu wider, or wrapping the text to the next line)?
    ![image](https://github.com/openedx/modular-learning/assets/945577/446cab88-5b78-45a7-991d-6cdb2e218c18)
7. **NEW** Please order the options in the **type filter** by hierarchy:
    - Section
    - Subsection
    - Unit
    - and then the components in whichever order (perhaps alphabetical)

Other fixes if possible:

8. After selecting a search result, the page zooms to the result in the course outline, but it seems to be “pinned” to the bottom of the page, rather than the top. It should appear closer to the top of the page.
    ![image](https://github.com/openedx/modular-learning/assets/945577/a5cf6a77-1131-4bf0-9857-055a05cd99dd)

**Comment by yusuf-musleh** [comment]
@bradenmacdonald Just had a few questions about this:

> 1. The focus state of the button outline has a rounded edge when it should have a square edge (to match the button shape).

For this one we want to make the changes in the paragon repo rather than styling in the course authoring mfe right?

> 3. For each result, the course/library name should only appear in the breadcrumbs when “all courses” is selected. (Currently, it shows for the results in “this course” too.)

I wasn't able to reproduce this. I only get the `Section` onwards in the breadcrumbs when searching in "This course". It only shows the course name in the breadcrumb when searching "All courses".

**This course**

<img width="1145" alt="Screenshot 2024-04-23 at 10 39 33 AM" src="https://github.com/openedx/modular-learning/assets/6829768/b8ea0dc4-3f42-453e-8e29-32bd7849422c">

**All courses**

<img width="1154" alt="Screenshot 2024-04-23 at 10 48 39 AM" src="https://github.com/openedx/modular-learning/assets/6829768/ff4e31b2-5e4d-4b3a-9c27-5024d70a0102">

Was this a specific case/condition where this occurs?

> 4. If I enter a search term that yields no results, I am unable to open the “type” filter. Change it to behave like the "Tags" filter and display a message like "No types in current results" in that case.

I wasn't able to reproduce this as well. I can still open the "Type" filter when there are no results found, and shows me a similar message to the "Tags" filter:

<img width="1188" alt="Screenshot 2024-04-23 at 10 45 35 AM" src="https://github.com/openedx/modular-learning/assets/6829768/c6b3990f-4af6-4069-8c32-59392ce1216f">

I tried it for both searching "This course" and "All courses". Was there also a special condition where this happens?

**Comment by yusuf-musleh** [comment]
@bradenmacdonald Got it 👍 , thanks!

**Comment by yusuf-musleh** [comment]
@bradenmacdonald Regarding the paragon bug, after looking into it I just wanted to confirm I understood the issue properly. In both cases, in our keyword search field and in the searchfield in the paragon docs you linked, the border radius in both is being set in the styles to be 0 (making it a square/rectangle), but the focus state remains on the original border radius.

The original border radius is being set/calculated [here](https://github.com/openedx/paragon/blob/784f604b0f3b612ad52ace8293a412a7bf54cab4/src/Button/_variables.scss#L50), from what I understand from the code, that should be automatically handling border radius [overrides](https://github.com/openedx/paragon/blob/784f604b0f3b612ad52ace8293a412a7bf54cab4/src/Button/_variables.scss#L41) but the bug is that it currently isn't?

**Comment by bradenmacdonald** [comment]
@yusuf-musleh  Ah, I see. I forgot how it worked. I guess it would be enough to just fix the CSS in course-authoring, where it makes the border square to also make the focus rectangle square. But we should open an issue on Paragon saying that the current Open edX theme doesn't provide a way to "force" buttons to be square easily, and show that the "SearchField"'s default submit button's focus rect doesn't match its border shape.

**Comment by yusuf-musleh** [comment]
@bradenmacdonald Make sense, thanks for the clarification. I'll make the style change in course authoring and create a issue in paragon mentioning the above.

**Comment by yusuf-musleh** [comment]
@bradenmacdonald Opened the issue on Paragon: https://github.com/openedx/paragon/issues/3038

**Comment by bradenmacdonald** [comment]
@yusuf-musleh  Based on some feedback from @ali-hugo, I added two items above in the description (6 and 7) - please take a look.
