### ISSUE TITLE
Enhancement to expand button in tag drawer - give authors opportunity to add tags when they expand any taxonomy

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/modular-learning#218]
As an author, when I click to expand a taxonomy in the tag drawer and it has no tags added yet, I expect to be able to start adding tags. Instead, I see an empty expanded space. I would expect to see the full tag list from which I could choose to add tags, and I don't immediately see the "edit tags" button on the bottom of the drawer. When I click on the expand button, I would like to see a link that tells me I have no tags yet but can add them. "No tags added yet. [Add tags +](#)"

Clicking that "Add tags +" link would have the same effect as clicking the "Edit tags" button that's below.

![Image](https://github.com/openedx/modular-learning/assets/95227019/9b2ccb16-df5e-4e22-bb86-e4070e11d97c)

**Comment by pomegranited** [comment]
@jmakowski1123 @bradenmacdonald  CC @ali-hugo I chose to use "Add tags" as the button text here instead of "Add tags +", because there was already an existing button by that name (and nowhere else uses the "+" convention).

![image](https://github.com/openedx/modular-learning/assets/7556571/253d15f2-7e0b-41cd-bc7f-1482ee47beac)

Is that ok?

**Comment by ali-hugo** [comment]
@pomegranited That makes sense to me. I'm happy with just plain "Add tags".
