### ISSUE TITLE
Bug: Draft version of component is copied on course

### ISSUE THREAD

**Issue by ChrisChV** [openedx/modular-learning#241]
If a user wants to add a library component using the library component picker, can only pick the published versions of the components. But when copying a component from the clipboard and pasting it into a course, the draft version is pasted.

Steps to reproduce:

1. Create a library in the Authoring MFE.
2. Create a component in your library with a name like "This is a test".
3. Publish the library.
4. Edit the component in your library, like "Edited component".
5. Copy the component to the clipboard.
6. Go to a course unit and paste the component. 
7. The draft version of the component is pasted. **Expected behavior:** The published version of the component is pasted.

**Comment by ChrisChV** [comment]
CC @bradenmacdonald @jmakowski1123

**Comment by bradenmacdonald** [comment]
@ChrisChV Thanks for carefully testing and reporting this. However, this is actually expected behavior. When you copy something, you copy exactly what you see, which may be a draft. If you copied something that said "A" and then you pasted it and it suddenly said "B", that would be confusing. (Principle of Least Surprise)

We actually [developed and tested this scenario carefully](https://github.com/openedx/edx-platform/blob/1a8c1e1c5da363c952c6f99f7c54c3a10c709b1e/cms/djangoapps/contentstore/helpers.py#L367-L373), so that for example when you copy version 5 (draft) and then go back to the library and publish it, nothing will show as changed in the course. But when you publish a new version 6, then the course will show that an update is now available.
