### ISSUE TITLE
Architectural discovery - should tagging be built as a separate service?

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/modular-learning#43]
_From Braden_:

We need to decide if tagging will be a separate service, or built into the LMS / Learning Core / etc.

Note that "taxonomy-connector", used by edx.org for skill tagging of videos and courses, is built as a library that's integrated into the discovery service: https://github.com/openedx/taxonomy-connector

Some prior tagging work was built as ["tagstore" within blockstore](https://github.com/openedx/blockstore/tree/master/tagstore#tagstore) but this approach was abandonded because the taxonomy models were not versioned in the same way that course content was.

**Comment by giovannicimolin** [comment]
**References:**

* https://discuss.openedx.org/t/when-to-make-a-new-backend-service/8267/7
* https://openedx.atlassian.net/wiki/spaces/AC/pages/1074397222/Architecture+Manifesto
* https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0057-proc-core-product.html
* https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0056-proc-architectural-advisory-process.html

**Comment by giovannicimolin** [comment]
# WIP

### Proposed implementation

Implement the new tagging service as a pluggable django app, and installed alongside learning-core in the edx-platform.

## Reasoning:

Tagging content is central to enable content re-use, facilitate the implementation of flexible content structures different from the current implementation and allow adaptive learning. 

At the same time, we don’t want to commit past mistakes as mentioned in [this post](https://discuss.openedx.org/t/when-to-make-a-new-backend-service/8267), so we should implement it as a separate Django App with clear boundaries and APIs, following the principles outlined in [OEP-49]() and in the [Architecture Manifesto]().

## Outstanding questions

* If the tagging service ends up eventually being used for content search and marketing, it’ll scale disproportionally compared to the other apps. Is that a problem we should be concerned about now?

…

* My understanding is that tagging content is part of the core of the platform, but tagging things with marketing purposes is not. Because of this, along with the requirement to make the new tagging system generic enough to accommodate both, should we implement it as a separate service?

I’ve had two ideas to address this concern:

* Implement generic “namespaces” that support different taxonomies/tags for the same content. If the APIs are complete and generic enough - then don’t need to bake in marketing specific code into the tagging capabilities (we’ll need strong adherence to best practices for this to work).
* Implement a “tagging-core”, basically a generic tagging library that can be reused on the learning core and wherever tagging is required (this can cause UI and code fragmentation, but separates content and marketing concerns). 


## Alternatives

### Implement it along learning-core
TBD

### Implementing tagging as Discovery service plugin
TBD

### Implement tagging as a new IDA
TBD

----

ADR (following [OEP-56](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0056-proc-architectural-advisory-process.html)) to follow once initial discussions here are done.

**Comment by giovannicimolin** [comment]
@bradenmacdonald @ormsbee @ChrisChV @jmakowski1123  This is ready for review.
I'm leaning towards option #1, but I'm curious to hear what you think. I also wrote a few concerns about each approach and on some, suggested solutions.

**Comment by ChrisChV** [comment]
@giovannicimolin Nice work!!

> I'm leaning towards option https://github.com/openedx/modular-learning/issues/1 - building it as a pluggable app and installing it along learning-core. Being able to use Python APIs and working on a single codebase improve developer experience and onboarding speed.
IMO the separate IDA is a bit of overkill, and discovery is a messy repo to work on.

I agree with you, one of the objectives of the tagging app is that it works in the current version of the content libraries and then with learning-core. I feel that with this first option it will be easier to achieve this :+1:

**Comment by bradenmacdonald** [comment]
I think option 1 makes sense, and I don't like option 2 because many people prefer/need to run the platform without the discovery service. Option 3 seems overkill without a compelling reason.

**Comment by ormsbee** [comment]
I'm in complete agreement with @bradenmacdonald. Let's roll with Option 1.

**Comment by giovannicimolin** [comment]
@ChrisChV @bradenmacdonald @ormsbee I created an ADR with the decisions from this thread in the `openedx-learning` repo.

**Comment by ChrisChV** [comment]
@jmakowski1123 The [ADR](https://github.com/openedx/openedx-learning/pull/40) for this issue was merged. I think we can put this task on Done
