### ISSUE TITLE
Wireframes for Copy/Paste

### ISSUE THREAD

**Issue by ormsbee** [openedx/modular-learning#6]
Full set of wireframes for Phase 1.

- #26
- #27 
- #28
- #29 
- #30
- #31

**Comment by ali-hugo** [comment]
@ormsbee

Please will you add me as the assignee for this task? Thanks!

**Comment by ali-hugo** [comment]
@ormsbee Hi again. I don't seem to have the permissions to move this ticket into "in progress". Please will you either enable my permissions, or do it for me. Thank you!

**Comment by ormsbee** [comment]
@ali-hugo: Added you to the project. Thank you!

**Comment by ali-hugo** [comment]
Hi @jmakowski1123. I don't see the ability to edit a ticket, so I'll add my thoughts here about how this ticket could be expanded upon.

The bulleted items below are possible subtasks. Please let me know what you think. I can create all the subtasks once we've confirmed the list. I have made a note next to the items that I have already started working on.

---

Full set of high-fidelity wireframes for Phase 1. 

- Copy component into clipboard and paste into same or different course _(in progress)_
- Copy unit into clipboard and paste into same or different course
- Copy subsection into clipboard and paste into same or different course _(in progress)_
- Copy section into clipboard and paste into same or different course
- View list of mismatched content/assets/settings and reconcile where possible (See #8 for full list of possible conflicts)
 _(in progress)_

---

P.s. Instead of "recreating" the Studio interface as a wireframe, I have been working on top of screenshots of Studio; so the "wireframes" are not strictly wireframes! You'll see what I mean when I share my working file next week.

**Comment by ormsbee** [comment]
@ali-hugo: Can you please check again to see if you have edit access to this ticket now?

**Comment by ali-hugo** [comment]
I do! Thanks @ormsbee

**Comment by jmakowski1123** [comment]
@ali-hugo This task list looks comprehensive to me! I don't see anything missing from the approach doc. I'm going to create a separate ticket/epic for usability testing.

**Comment by ali-hugo** [comment]
@jmakowski1123 @ormsbee  @sarina @bradenmacdonald 

Hi everyone,

I thought I'd share my working file for the _Modular Learning_ wireframes so that you could see the progress so far (you should have received an invite from Figma). There is still a _long_ way to go, and some screens are still very rough! So please excuse any rough notes or half-complete user flows you might spot throughout the file. 

Feel free to add comments and questions directly to Figma if you would like to. Otherwise, I'm keeping an eye on any updates that are added to the wiki.

[Here is a link](https://www.figma.com/file/y2qfzidTxxfYK8ONgyT7KP/Modular-Learning-Wireframes?node-id=0%3A1&t=vLw169tYqd3OV7n5-1) to the file. Please let me know if you have any trouble accessing it.

**Comment by ali-hugo** [comment]
Just to add to my previous comment: I imagine some of the interactions/components I've suggested may be beyond the scope of Phase 1. I can scale back anything that is too complex.

**Comment by bradenmacdonald** [comment]
Thanks @ali-hugo !

Here's some early feedback from me.

* I agree with @ormsbee's point. For example, I would suggest removing the "Right-hand display of clipboard preview" since we already have same thing appearing in the header with the new clipboard icon. Also, I found it very hard to even notice the right-hand display. I think the right side of Studio is so useless that I have trained myself to completely ignore everything that appears there :p So if we do keep it there, I think it would help if it looked visually different than the current UI. But I don't think we need the same thing in two places, especially because in 99% of cases people will be very quickly copying and pasting and they will know exactly what they just copied needing a UI to remind them.
* For the paste buttons, I think the (?) icons are a bit distracting or inconsistent with the rest of the UI? We could still show the same explanatory popups when people hover their cursor over the disabled buttons, even without indicating it with the (?). Not sure though, just my two cents.

**Comment by jmakowski1123** [comment]
@ormsbee @bradenmacdonald Besides the view/presence of the clipboard on the sidebar, is there an a priori shortlist of ways/guidelines to keep in mind, in order to keep this feature on the pluggable end of the spectrum? Or is it easier to identify in real-time as they pop up?

**Comment by ormsbee** [comment]
@jmakowski1123: I'm not as competent on the frontend as @bradenmacdonald, @arbrandes, and others–so my assessment of what is and isn't hard may be skewed by my backend-focused background. But generally speaking, I think the fewer places in the UI layout that we touch, the fewer extension points we will need, and the easier this will be to implement this as a plugin. The simpler those areas of UI interaction with "core" Studio are, the easier it is.

For instance, on the relatively easy end of the spectrum, there's that calculator that floats on the bottom of the LMS for some courses if you enable the right options. It's basically its own self-contained little world and does not require interaction with the rest of the page. Now that clearly wouldn't be sufficient for the clipboard feature, but I include it just to give an extreme example.

For the sake of the next example, I'm going to assume that we're building all the pieces of UI in a way that would be pluggable/extensible so that this could be built entirely as a plugin. **For the sake of getting an MVP out without boiling the ocean, this is almost certainly not the way we'll actually build it.** But in the long term, we'll probably want it to look something like this for people developing features.

Say we have a box somewhere that our plugin owns entirely. It's some kind of hovering, expanding box in the UI somewhere. Changes in there are cheap, because we don't need to make any sort of API stability guarantees to anyone. Maybe the preview goes in there, maybe error messages–whatever functionality goes in there is stuff that Studio as a whole doesn't need to really understand anything about. We can kind of go wild in that space, do fancy stuff, change our minds and completely revamp the UI from one iteration to the next, etc.

The UI elements that are in common spaces are ones where we have to make longer term promises, and it makes it easier to maintain these things if they're simple. So for instance, take the copy animation:

![copy_button_spinner](https://user-images.githubusercontent.com/41625/205807327-a74129bb-09e8-445e-96ad-63dc972811f2.png)

The copy button built on the simplest possible extension point might just emit an event that basically says, "button `copy` was pressed for subsection `<usage_key>`". The plugin would provide the ID and image for the button, would listen for when it gets pressed, and then do something in response. But the extension point stops caring at that point.

When we add the animation for the copy button, the relationship gets more complex. Now in addition to emitting that event when the button is pressed, the extension point is going to listen for events that tell it to update the state of that button (un-clicked, in-progress, success?, failure?). But what if they reload the page? Does the plugin also need to set the initial state of that icon on the Outline's page load to show that it's still copying? Does it disable all other copy buttons while that's happening? It's not just that we have to handle these situations, it's that the extension point API promises that we're offering to all future plugins has to grow these features to accommodate this use case.

So my rough rule of thumb of plugin-friendliness is that the more complex an interaction is, the more we want to stuff it into a box that the plugin entirely controls. When we have an extension point where we might expect a bunch of plugins to make use of in a shared space (e.g. the copy button), we should keep that interface as simple as possible.

**Comment by ali-hugo** [comment]
@ormsbee @bradenmacdonald @jmakowski1123 

Thanks for all your comments, both here and in Figma. You've given me a lot to work with!

Dave:
> So my question is: Can we reduce the footprint of this feature so that there are fewer touch-points, without harming the usability of this feature?

Yes - we will find a way! I'm going to try out a few options today. I'll let you know when I have something worth showing to you all.

> So my rough rule of thumb of plugin-friendliness is that the more complex an interaction is, the more we want to stuff it into a box that the plugin entirely controls. 

This is a helpful explanation. Thanks Dave!

Braden:
> ...I would suggest removing the "Right-hand display of clipboard preview" since we already have same thing appearing in the header with the new clipboard icon. 

Makes sense. I'll remove the sidebar clipboard.

> I think the right side of Studio is so useless that I have trained myself to completely ignore everything that appears there :p 

Haha, good to know! What do you think of my idea to move the information about the start date, pacing type, checklists, and course highlight emails from the top of the screen to the sidebar (and remove everything else)? It looks cleaner to me. That said, the sidebar space might be better used for some of the future additions that @ormsbee mentioned (e.g. metadata tagging, insert-from-template, etc). Food for thought.

> For the paste buttons, I think the (?) icons are a bit distracting or inconsistent with the rest of the UI? We could still show the same explanatory popups when people hover their cursor over the disabled buttons, even without indicating it with the (?). 

The (?)'s bug me too, but I think removing them would introduce accessibility issues. See the "If we really have to set a button or input to disabled" section in [this article](https://naga.co.za/2021/08/06/accessibility-and-usability-considerations-for-disabling-buttons-and-inputs/). It would be great if we could run the wireframes by someone who knows a lot about accessibility; I am in no way an expert.

**Comment by ormsbee** [comment]
@brian-smith-tcril: Thank you for commenting–I know your understanding of frontend pluggability is much better than mine. FWIW, my concern isn't about short term implementation complexity, but long term issues around independently developing/maintaining a plugin over time, and maintaining backwards extension points in Studio as we go from release to release and the Studio UI evolves.

Do you think my concerns there are overblown? When it comes to something like the "copy" button–is it fine if Studio lets plugins provide button components for all the rows where it has to be rendered in a page, and delegates behavior to the plugin? Does that have any implications on whether the plugin code is built during Studio frontend deployment or separately deployed?

**Comment by brian-smith-tcril** [comment]
> Do you think my concerns there are overblown?

Not at all! It's always good to think about how UX changes touch long term maintainability.

> is it fine if Studio lets plugins provide button components for all the rows where it has to be rendered in a page

I don't see any issues there. We could build out a "plugin button container" or something like that and allow runtime configuration of what plugin buttons display where (with reasonable default values to the best of our abilities).

> Does that have any implications on whether the plugin code is built during Studio frontend deployment or separately deployed?

Handling it as a separate deployment will probably add a bit of complexity, but it doesn't feel insurmountable to me.

**Comment by bradenmacdonald** [comment]
What I've done in other apps is just allow plugins to inject arbitrary React components into pre-defined slots like `per-item-action-toolbar`, `add-component-row` etc. Then if the plugin wants a simple button, it's just a simple button, and if the plugin wants a fancy button with loading spinner and a related modal or rich tooltip, it can do that too. If there are enough slots in the UI, the plugin can integrate as thoroughly as shown in the original mockups without any code changes to the underlying MFE. However, openedx MFEs don't actually support plugins yet and are subject to refactoring that could lead to high maintenance costs if we go that route too early. So for now I agree that keeping the number of touchpoints minimal will make the implementation simpler.

**Comment by jmakowski1123** [comment]
Frames complete, 2/17.

**Comment by bradenmacdonald** [comment]
@ali-hugo  In response to your question on Figma, here's how block-specific errors are currently shown in Studio. I think there's also a "warning" version which is very similar but yellow instead of grey/orange.

![Screenshot 2023-02-17 at 1 58 31 PM](https://user-images.githubusercontent.com/945577/219801676-c9d57aa2-3686-478a-92b4-9f793e650f1c.png)

**Comment by ali-hugo** [comment]
@bradenmacdonald Thanks! That's helpful. 

I think it's a good idea to use the default styling of inline comments for the MVP. I've asked Jenna and Jon to confirm ([here in Figma](https://www.figma.com/file/y2qfzidTxxfYK8ONgyT7KP?node-id=936:763#370741457)). 

> I think there's also a "warning" version which is very similar but yellow instead of grey/orange.

The orange alerts in the wireframes are actually supposed to be warnings, not errors (Paragon uses red for errors and yellow for warnings; the only reason I made warnings orange was to tie in with the rest of the Studio interface). How much effort is it to change the colour of Studio's alerts? Would it make more sense to stick to Studio's default colours for the MVP (i.e. orange for errors and yellow for warnings)? FYI @jmakowski1123

**Comment by jmakowski1123** [comment]
@ali-hugo I'd stick to the current default colors for now, assuming that they'll eventually get "fixed" whenever the 2U team prioritizes those Studio pages for paragon updates.

**Comment by ali-hugo** [comment]
@jmakowski1123 
> I'd stick to the current default colors for now

Will do. I'll update the colours in the wireframes to reflect the current default colours. 

@bradenmacdonald 
> I think there's also a "warning" version which is very similar but yellow instead of grey/orange.

You're right. I just found an example in the docs:

<img width="727" alt="Screenshot 2023-02-22 at 14 46 40" src="https://user-images.githubusercontent.com/88187719/220623760-6cf77b3b-ffb6-4cb7-b1a0-fa2c1e98290e.png">

Updating the colours in Figma as we speak ;)
